name: Pull Request Docs Check

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.13
    - name: Install dependencies
      run: |
          sudo apt-get update -y && sudo apt-get install -y git git-core libxml2-dev libxslt-dev python3.10-dev
          sudo python -m pip install --upgrade pip
          sudo pip install -r requirements.freeze.txt
    - name: Make output folder
      run: mkdir _build
    - name: Clone master branch
      run: git clone "https://${{ secrets.ACCESS_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git" --no-checkout --branch gh-pages --single-branch ./_build # git clone "https://${{ secrets.ACCESS_TOKEN }}@github.com/${GITHUB_ACTOR}/${GITHUB_ACTOR}.github.io.git" --branch master --single-branch ./_build
    - name: Generate static pages
      run: BASE_URL="https://"${GITHUB_REPOSITORY/\//.github.io\/} YANDEX_METRIKA_ID="${{ secrets.YANDEX_METRIKA_ID }}" sphinx-build -W -D language=ru -b html . _build
